### PR TITLE
feat(TextArea): Created styled TextArea component for web. 

### PR DESCRIPTION
**Pull request by austinspaeth**
Referencing issue #131 .. Added a <TextArea> styled component using the same API as <TextInput>. Iterations were made for AMP, Web and Native.

### CODE REVIEW

**Comment by kamleshchandnani** [comment]
Deploy preview for *leaf-ui* processing.

Built with commit 7adaaf4623abb756b20961f172ab8cad1e55b453

https://app.netlify.com/sites/leaf-ui/deploys/5bc5803502ed8362160a798c

**Comment by kamleshchandnani** [comment]
Hey @austinspaeth, 

First of all welcome to leaf-ui 🎉and Congratulations on your first PR to leaf-ui 🕺 

Thank you and I really appreciate your efforts to help us make leaf-ui better by raising a PR's  🙌 

We consider each and every contribution valuable and more than that we love contributions 🏅

We have some contributing guidelines listed [here](https://github.com/treebohotels/leaf-ui/blob/master/CONTRIBUTING.md) which also has a section about [Submitting Changes](https://github.com/treebohotels/leaf-ui/blob/master/CONTRIBUTING.md#submitting-changes). It would be good if you can follow the same commit process since we have automated release pipeline which entirely depends on it. We can merge this PR quickly post that. 🙂

**Comment by austinspaeth** [comment]
@kamleshchandnani Oops! I added the export to `TextArea/amp/index.js` and I removed the .DS_Store. Thanks!

**Comment by austinspaeth** [comment]
@kamleshchandnani Oops! I added the export to `TextArea/amp/index.js` and I removed the .DS_Store. Thanks!

**Comment by kamleshchandnani** [comment]
@austinspaeth Awesome! The PR looks good to me 🙂👍
@kashishgrover Can you please have a look as well from your end for native implementation?  
We are good to merge this then 🎉

**Comment by kamleshchandnani** [comment]
Hey @austinspaeth <https://github.com/austinspaeth>,
I couldn't find your commits on GitHub. Did you remove them or something's
broken from GitHub's end?

Thanks & Regards,
Kamlesh Chandnani
Cell: +91 8000142880

**Comment by austinspaeth** [comment]
Very weird! It might have been Github's outages last night? If they don't reappear, I can push them up again.

**Comment by kamleshchandnani** [comment]
@austinspaeth
Yay! Your PR got merged 🎉
Thanks for your valuable contribution ❤️ 
Happy Hacktoberfest 👨‍💻

**Pull request merged**
